# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KelaContactProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('legalName', models.CharField(max_length=120)),
                ('firstName', models.CharField(blank=True, max_length=120)),
                ('additionalName', models.CharField(blank=True, max_length=120)),
                ('lastName', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('zipCode', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KelaInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('companyName', models.CharField(max_length=120)),
                ('firstName', models.CharField(max_length=120)),
                ('additionalName', models.CharField(blank=True, max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('zipCode', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vatId', models.CharField(max_length=20)),
                ('iban', models.CharField(max_length=40)),
                ('bic', models.CharField(max_length=40)),
                ('serviceproviderType', models.CharField(choices=[('PALVELUNTUOTTAJA', 'Kuntoutuspalvelutuottaja'), ('LASKUTTAJA', 'Laskuttaja kuntoutuspalveluntuottajan puolesta')], default='PALVELUNTUOTTAJA', max_length=40)),
                ('invoiceRefType', models.CharField(choices=[('VIITENUMERO', 'Viitenumero'), ('TILITYSNRO', 'Tilityksen numero')], default='TILITYSNRO', max_length=40)),
                ('taxAdvanceType', models.CharField(choices=[('TAXREGISTER', 'Ennakkoperintärekisterissä'), ('TAXDEDUCTIONCARD', 'Verokortti')], default='TAXREGISTER', max_length=40)),
                ('date', models.DateField(null=True)),
                ('paidDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KelaInvoiceCompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('companyName', models.CharField(max_length=120)),
                ('firstName', models.CharField(max_length=120)),
                ('additionalName', models.CharField(blank=True, max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('zipCode', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vatId', models.CharField(max_length=20)),
                ('iban', models.CharField(max_length=40)),
                ('bic', models.CharField(max_length=40)),
                ('serviceproviderType', models.CharField(choices=[('PALVELUNTUOTTAJA', 'Kuntoutuspalvelutuottaja'), ('LASKUTTAJA', 'Laskuttaja kuntoutuspalveluntuottajan puolesta')], default='PALVELUNTUOTTAJA', max_length=40)),
                ('invoiceRefType', models.CharField(choices=[('VIITENUMERO', 'Viitenumero'), ('TILITYSNRO', 'Tilityksen numero')], default='TILITYSNRO', max_length=40)),
                ('taxAdvanceType', models.CharField(choices=[('TAXREGISTER', 'Ennakkoperintärekisterissä'), ('TAXDEDUCTIONCARD', 'Verokortti')], default='TAXREGISTER', max_length=40)),
                ('companyProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.CompanyProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KelaInvoiceCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(max_length=120)),
                ('additionalName', models.CharField(blank=True, max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('ssn', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('zipCode', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('telephone', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.BooleanField(default=True)),
                ('therapyCategory', models.CharField(choices=[('NEUROPSYKOLOGINEN', 'Neuropsykologinen kuntoutus'), ('MUSIIKKI', 'Musiikkiterapia'), ('KUNTOUTUS', 'Kuntoutusterapia'), ('LAUSUNTO', 'Lausunto'), ('MUUSYY', 'Muuta, mikä?')], default='KUNTOUTUS', max_length=40)),
                ('sessionprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sessionpriceKelaRefund', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KelaInvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('sessionInvoiceType', models.CharField(choices=[('DOUBLESESSION', 'Kaksoiskäynti'), ('SINGLESESSION', 'Terapiakäynti'), ('HALFPRICEINTRODUCTION', 'Tutustumiskäynti puoleenhintaan'), ('FREEINTRODUCTION', 'Ilmainen tutustumiskäynti')], default='SINGLESESSION', max_length=40)),
                ('kelaInvoiceType', models.CharField(choices=[('NOKELAINVOICE', 'Kela ei maksa käyntiä'), ('CANINVOICEKELA', 'Kela maksaa osan käynnistä')], default='CANINVOICEKELA', max_length=40)),
                ('sessionType', models.CharField(choices=[('RYHMÄ', 'Ryhmäkäynti'), ('PERHE', 'Perhekäynti'), ('MUU', 'Muu käynti'), ('PARI', 'Parikäynti'), ('YKSILÖ', 'Yksilöterapia'), ('OHJAUS', 'Ohjauskäynti')], default='YKSILÖ', max_length=40)),
                ('sessionDone', models.BooleanField(default=False)),
                ('kelaInvoiced', models.BooleanField(default=False)),
                ('customerInvoiced', models.BooleanField(default=False)),
                ('sessionprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sessionpriceKelaRefund', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kelaInvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelainvoicing.KelaInvoice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KelaStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('companyName', models.CharField(max_length=120)),
                ('firstName', models.CharField(max_length=120)),
                ('additionalName', models.CharField(blank=True, max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('zipCode', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vatId', models.CharField(max_length=20)),
                ('iban', models.CharField(max_length=40)),
                ('bic', models.CharField(max_length=40)),
                ('serviceproviderType', models.CharField(choices=[('PALVELUNTUOTTAJA', 'Kuntoutuspalvelutuottaja'), ('LASKUTTAJA', 'Laskuttaja kuntoutuspalveluntuottajan puolesta')], default='PALVELUNTUOTTAJA', max_length=40)),
                ('invoiceRefType', models.CharField(choices=[('VIITENUMERO', 'Viitenumero'), ('TILITYSNRO', 'Tilityksen numero')], default='TILITYSNRO', max_length=40)),
                ('taxAdvanceType', models.CharField(choices=[('TAXREGISTER', 'Ennakkoperintärekisterissä'), ('TAXDEDUCTIONCARD', 'Verokortti')], default='TAXREGISTER', max_length=40)),
                ('date', models.DateField()),
                ('orderno', models.CharField(blank=True, max_length=120)),
                ('invoiceRef', models.CharField(blank=True, max_length=120)),
                ('taxAdvanceExplanation', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kelainvoicecompanyprofile',
            name='kelaStatement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelainvoicing.KelaStatement'),
        ),
        migrations.AddField(
            model_name='kelainvoice',
            name='kelaInvoiceCustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelainvoicing.KelaInvoiceCustomer'),
        ),
        migrations.AddField(
            model_name='kelainvoice',
            name='kelaStatement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelainvoicing.KelaStatement'),
        ),
    ]
